### ISSUE TITLE
href="#" duplicates the page into the previewer

### ISSUE THREAD

**Issue by BobbyESP** [midudev/codi.link#180] opened 2021-11-11 23:25 UTC
When having an href with the value of "#", the hole codi.link page gots duplicated into the web previewer.

https://user-images.githubusercontent.com/60316747/141383048-f0dfe00b-7b1f-43a8-92df-89192674e554.mp4

**Comment by QuevedoIB** [comment] 2021-11-23 21:12
This issue is a duplicate of #163

**Comment by midudev** [comment] 2022-01-31 08:58
Duplicated

**Closed by midudev** 2022-01-31 08:58 UTC
